# Targets to run solutions e.g:
# cd 2024
#make run-day1-demo
#make run-day1-actual

# Makefile for Day 01 of the 2024 Advent of Code
run-day1-demo:
	cd Day01 && dotnet run --demo

run-day1-actual:
	cd Day01 && dotnet run --actual

# Makefile for Day 02 of the 2024 Advent of Code
run-day2-demo:
	cd Day02 && dotnet run --demo

run-day2-actual:
	cd Day02 && dotnet run --actual

# Makefile for Day 03 of the 2024 Advent of Code
run-day3-demo:
	cd Day03 && dotnet run --demo

run-day3-actual:
	cd Day03 && dotnet run --actual

# Makefile for Day 04 of the 2024 Advent of Code
run-day4-demo:
	cd Day04 && dotnet run --demo

run-day4-actual:
	cd Day04 && dotnet run --actual