# Targets to run solutions e.g:
# cd 2024
#make run-day1-demo
#make run-day1-actual

# Makefile for Day 01 of the 2024 Advent of Code
run-day1-demo:
	cd Day01 && dotnet run --demo

run-day1-actual:
	cd Day01 && dotnet run --actual